import Head from "next/head";
import React from "react";

import ReportsPage from "@/templates/ReportsPage";

export default function Financial() {
    return (
        <>
            <Head>
                <title>Wolfy Admin - Relatórios</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ReportsPage />
        </>
    );
}
