import Head from "next/head";

import LandingPage from "@/templates/LandingPage";

export default function Home() {
    return (
        <>
            <Head>
                <title>Wolfy Admin</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LandingPage />
        </>
    );
}
