import Head from "next/head";
import React from "react";

import RequerentsPage from "@/templates/RequerentsPage";

export default function Products() {
    return (
        <>
            <Head>
                <title>Wolfy Admin - Requerentes</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RequerentsPage />
        </>
    );
}
