import { DataTypes,Model } from "sequelize";
import { sequelize } from "../instances/postgres";

export interface Venda extends Model{
    id: number,
    idProdutor:number,
    idCliente:number,
    idTransacao:string,
    checkoutLink:string,
    nome:string,
    email:string,
    cpf:string,
    celular:string,
    cep:string,
    rua:string,
    numero:string,
    bairro:string,
    cidade:string,
    estado:string,
    complemento:string,
    assinatura:string,
    status:string,
    valor:number,
    tipo:string,
    cupomName:string,
    url:string,
    compensacao:boolean,
    data:Date,
    hora:TimeRanges,
    parcelas:number,
    valorLiquido:number,
    valorRetido:number,
    ip:string,
    clientUserAgent:string
}
export const Venda = sequelize.define<Venda>('venda',{
    id:{
        primaryKey:true,
        autoIncrement:true,
        type:DataTypes.NUMBER
    },
    idProdutor:{
        type:DataTypes.NUMBER
    },
    idCliente:{
        type:DataTypes.NUMBER
    },
    idTransacao:{
        type:DataTypes.STRING
    },
    checkoutLink:{
        type:DataTypes.NUMBER
    },
    nome:{
        type:DataTypes.STRING
    },
    email:{
        type:DataTypes.STRING
    },
    cpf:{
        type:DataTypes.STRING
    },
    celular:{
        type:DataTypes.STRING
    },
    cep:{
        type:DataTypes.STRING
    },
    rua:{
        type:DataTypes.STRING
    },
    numero:{
        type:DataTypes.STRING
    },
    bairro:{
        type:DataTypes.STRING
    },
    cidade:{
        type:DataTypes.STRING
    },
    estado:{
        type:DataTypes.STRING
    },
    complemento:{
        type:DataTypes.STRING
    },
    assinatura:{
        type:DataTypes.STRING
    },
    status:{
        type:DataTypes.STRING
    },
    valor:{
        type:DataTypes.FLOAT
    },
    tipo:{
        type:DataTypes.STRING
    },
    cupomName:{
        type:DataTypes.STRING
    },
    url:{
        type:DataTypes.STRING
    },
    compensacao:{
        type:DataTypes.BOOLEAN
    },
    data:{
        type:DataTypes.DATE
    },
    hora:{
        type:DataTypes.TIME
    },
    parcelas:{
        type:DataTypes.NUMBER
    },
    valorLiquido:{
        type:DataTypes.NUMBER
    },
    valorRetido:{
        type:DataTypes.NUMBER
    },
    ip:{
        type:DataTypes.STRING
    },
    clientUserAgent:{
        type:DataTypes.STRING
    }
},{
    tableName:'venda',
    timestamps:false
})