import Head from "next/head";
import React from "react";
import UserPage from "@/templates/UserPage";

export default function User() {
    return (
        <>
            <Head>
                <title>Wolfy Admin - Usuário</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <UserPage />
        </>
    );
}
